### ISSUE TITLE
Build error when using SelectAsync on extended IOntraportBaseCustomObject

### ISSUE THREAD

**Issue by RedJandal** [mysteryx93/OntraportApi.NET#2]
Hi,

First of all thanks for all the hard work on this project.

After upgrading from v 1.0.1 to version 1.2.2 I get the following errors wherever I have an interface that extends IOntraportBaseCustomObject and the SelectAsync method is called.

`public interface IOntraportRecordings : IOntraportBaseCustomObject<MyCustomObject>
{ }`

The error I get when I try to build is:

The call is ambiguous between the following methods or properties: 'IOntraportBaseRead<T>.SelectAsync(int, CancellationToken)' and 'IOntraportBaseRead<T>.SelectAsync(int, CancellationToken)

When I downgraded to 1.0.1 and change all the namespaces back to the old ones it builds fine.

I am wondering if there is a circular reference somewhere.

**Comment by mysteryx93** [comment]
I believe this issue has been fixed, and I just released v1.2.4, can you check that it's working now?

**Comment by RedJandal** [comment]
This issue is still present in version 1.2.4

**Comment by mysteryx93** [comment]
It more looks like a DLL reference confusion problem. There is only 1 such method defined in the interface, but it looks like it has 2 different versions loaded and doesn't know which DLL to use. Double-check your project files for reference problems.
