### ISSUE TITLE
SelectAsync Exception

### ISSUE THREAD

**Issue by ghost** [mysteryx93/OntraportApi.NET#3]
When I use NetFramework 4.8 in SelectAsync() throw this exception 
![image](https://user-images.githubusercontent.com/14035264/124190622-f843a900-da98-11eb-88d1-f4862daac05b.png)

Posible solution in SendRequestAsync:
            using var request = new HttpRequestMessage(method, requestUrl)
            {
                Content = method.Method == "GET" ? null : new StringContent(content, Encoding.UTF8, encodeJson ? ContentJson : ContentUrl)
            };

**Comment by mysteryx93** [comment]
Does it crash only in .NET 4.8 ? What's the usage that causes problem

**Comment by mysteryx93** [comment]
OK I think I see the problem, I send `StringContent("")` which may work in .NET Core but crash in .NET 4.8. Should set content to null instead.
